# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d930f872f4310bc0dfa14f5ac3d93fcebd56213cce14335a9e11ade9409466c689fb40394b20a7a43a0cff83cc6e2a8046fbcd64aaa4b525ba5854a834f556ad

test:
  secret_key_base: 67bca7d04932eec1584516b507f21f1b484a2083b5f35699db883ca7b33f36b4034d298a1cca586a5b0e74fcf574ab57f5c0468861fa8d4772d074be7e8e0b62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
